### ISSUE TITLE
1.4 版本启动报错 Input string was not in a correct format

### ISSUE THREAD

**Issue by AkashiCoin** [123456fsdaf/GenshinImpact_Lanucher#16]
以下为日志
```
Input string was not in a correct format.   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at GenshinImpact_Lanucher.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by 123456fsdaf** [comment]
如何重现此bug?

**Comment by AkashiCoin** [comment]
> 如何重现此bug?

这里下载下来都出现了这个错误，有好几个人都是这样

**Comment by 123456fsdaf** [comment]
这个错误提示仅仅是提示出现在什么函数中错误，而且我看了也找不到我的函数，这个BUG是怎么出现的，是点击什么按钮，执行什么操作后出现的

**Comment by yajiwa** [comment]
直接打开exe就会这样，不知是不是.Net6版本不同的原因，我试了多个版本都是这个错

**Comment by 123456fsdaf** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.203-windows-x64-installer
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.203-windows-x86-installer

请尝试上面两个连接

**Comment by yajiwa** [comment]
依然会报上面的错误

**Comment by 123456fsdaf** [comment]
请说一下系统版本

**Comment by yajiwa** [comment]
win10

**Comment by 123456fsdaf** [comment]
可能是Mica不兼容的情况，到我的文档——GSIConfig——Config——LauncherConfig.ini

在Style之下修改或添加IsMica=False

**Comment by 123456fsdaf** [comment]
![image](https://user-images.githubusercontent.com/65759143/170854892-ab91207e-3bcc-4eb7-855d-2d9573386681.png)

**Comment by 123456fsdaf** [comment]
修改完毕后，如果还出现错误，请等待今天晚上的修复

**Comment by yajiwa** [comment]
好的，刚刚去这个文件看了没有生成Style配置
![image](https://user-images.githubusercontent.com/58063798/170855138-de30eb8f-9907-426f-b0ce-ef3f3067617d.png)
因为对修复有帮助

**Comment by 123456fsdaf** [comment]
https://github.com/123456fsdaf/GenshinImpact_Lanucher/releases/tag/1.4.1-bate

**Comment by 123456fsdaf** [comment]
已经发布临时修复

**Comment by GuteNachte** [comment]
用了临时修复版本还是出现了一样的报错

**Comment by 123456fsdaf** [comment]
https://github.com/123456fsdaf/GenshinImpact_Lanucher/releases/tag/1.4.1
正式修复

**Comment by Stevwrz** [comment]
我使用1.41仍然有同样的问题

**Comment by 123456fsdaf** [comment]
请删除配置文件，以及重启应用，尽量不要使用Win10以下系统，目前并未全部支持
